// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQGBIyyiPBAqLPcSlb7Pq1Yy1N2DaG-o',
    appId: '1:1009931864210:web:3385a129fca5284af53e4b',
    messagingSenderId: '1009931864210',
    projectId: 'task-express-273db',
    authDomain: 'task-express-273db.firebaseapp.com',
    storageBucket: 'task-express-273db.firebasestorage.app',
    measurementId: 'G-DH0M6Y9CSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakw_jfXQmveyvTfGDNohUK-XLdCh9_68',
    appId: '1:1009931864210:android:2a364e717934af1ff53e4b',
    messagingSenderId: '1009931864210',
    projectId: 'task-express-273db',
    storageBucket: 'task-express-273db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePHfX0yYJ16DWkrKVFAu9lt5kPoKB2sc',
    appId: '1:1009931864210:ios:0006673f00d0d237f53e4b',
    messagingSenderId: '1009931864210',
    projectId: 'task-express-273db',
    storageBucket: 'task-express-273db.firebasestorage.app',
    iosBundleId: 'com.sp.worknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePHfX0yYJ16DWkrKVFAu9lt5kPoKB2sc',
    appId: '1:1009931864210:ios:0006673f00d0d237f53e4b',
    messagingSenderId: '1009931864210',
    projectId: 'task-express-273db',
    storageBucket: 'task-express-273db.firebasestorage.app',
    iosBundleId: 'com.sp.worknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCQGBIyyiPBAqLPcSlb7Pq1Yy1N2DaG-o',
    appId: '1:1009931864210:web:8fb1bc8365061f72f53e4b',
    messagingSenderId: '1009931864210',
    projectId: 'task-express-273db',
    authDomain: 'task-express-273db.firebaseapp.com',
    storageBucket: 'task-express-273db.firebasestorage.app',
    measurementId: 'G-L0WWT4GRBM',
  );
}
