part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const BOTTOM = _Paths.BOTTOM;
  static const WORKNEST = _Paths.WORKNEST;
  static const BOOKING = _Paths.BOOKING;
  static const SETTING = _Paths.SETTING;
  static const CHAT = _Paths.CHAT;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const SPLASH1 = _Paths.SPLASH1;
  static const SPLASH2 = _Paths.SPLASH2;
  static const SPLASH3 = _Paths.SPLASH3;
  static const LOGIN = _Paths.LOGIN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const JOIN = _Paths.JOIN;
  static const LOCATION = _Paths.LOCATION;
  static const OTP = _Paths.OTP;
  static const PROFILE = _Paths.PROFILE;
  static const TILE_FIXING_HELPER = _Paths.TILE_FIXING_HELPER;
  static const CEMENT_HELPER = _Paths.CEMENT_HELPER;
  static const PLASTERING_HELPER = _Paths.PLASTERING_HELPER;
  static const BRICKLAYING_HELPER = _Paths.BRICKLAYING_HELPER;
  static const SCAFFOLDING_HELPER = _Paths.SCAFFOLDING_HELPER;
  static const ROAD_CONSTRUCTION_HELPER = _Paths.ROAD_CONSTRUCTION_HELPER;
  static const PROFESSIONAL_PLUMBER = _Paths.PROFESSIONAL_PLUMBER;
  static const PROFESSIONAL_PROFILE = _Paths.PROFESSIONAL_PROFILE;
  static const HELPER_PROFILE = _Paths.HELPER_PROFILE;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const ADD_ADDRESS = _Paths.ADD_ADDRESS;
  static const VERIFICATION = _Paths.VERIFICATION;
  static const CHAT_SCREEN = _Paths.CHAT_SCREEN;
  static const BOOKING_CONFIRM = _Paths.BOOKING_CONFIRM;
  static const SERVICE_COMPLETED = _Paths.SERVICE_COMPLETED;
  static const SERVICE_COMPLETED_SUCCESSFULLY =
      _Paths.SERVICE_COMPLETED_SUCCESSFULLY;
  static const ADDRESS_SCREEN = _Paths.ADDRESS_SCREEN;
  static const PROVIDER_LOGIN = _Paths.PROVIDER_LOGIN;
  static const PROVIDER_OTP = _Paths.PROVIDER_OTP;
  static const PROVIDER_LOCATION = _Paths.PROVIDER_LOCATION;
  static const PROVIDER_PROFILE = _Paths.PROVIDER_PROFILE;
  static const PROVIDER_HOME = _Paths.PROVIDER_HOME;
  static const ACTIVEJOB_SCREEN = _Paths.ACTIVEJOB_SCREEN;
  static const BOTTOM2 = _Paths.BOTTOM2;
  static const JOBS = _Paths.JOBS;
  static const PROVIDER_SETTING = _Paths.PROVIDER_SETTING;
  static const PROVIDER_CHAT = _Paths.PROVIDER_CHAT;
  static const PROVIDER_ACCOUNT = _Paths.PROVIDER_ACCOUNT;
  static const PROVIDER_CHAT_SCREEN = _Paths.PROVIDER_CHAT_SCREEN;
  static const PROVIDER_EDIT_PROFILE = _Paths.PROVIDER_EDIT_PROFILE;
  static const JOB_DETAIL = _Paths.JOB_DETAIL;
  static const YOUR_EARNING = _Paths.YOUR_EARNING;
  static const JOBS_DETAILS = _Paths.JOBS_DETAILS;
  static const HELP_SUPPORT = _Paths.HELP_SUPPORT;
  static const USER_HELP = _Paths.USER_HELP;
  static const REQUEST_PANDDING = _Paths.REQUEST_PANDDING;
  static const ABOUT_TASKEXPRESS = _Paths.ABOUT_TASKEXPRESS;
  static const PRIVACYDATA_VIEW = _Paths.PRIVACYDATA_VIEW;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const BOTTOM = '/bottom';
  static const WORKNEST = '/worknest';
  static const BOOKING = '/booking';
  static const SETTING = '/setting';
  static const CHAT = '/chat';
  static const ACCOUNT = '/account';
  static const SPLASH1 = '/splash1';
  static const SPLASH2 = '/splash2';
  static const SPLASH3 = '/splash3';
  static const LOGIN = '/login';
  static const SIGN_UP = '/sign-up';
  static const JOIN = '/join';
  static const LOCATION = '/location';
  static const OTP = '/otp';
  static const PROFILE = '/profile';
  static const TILE_FIXING_HELPER = '/tile-fixing-helper';
  static const CEMENT_HELPER = '/cement-helper';
  static const PLASTERING_HELPER = '/plastering-helper';
  static const BRICKLAYING_HELPER = '/bricklaying-helper';
  static const SCAFFOLDING_HELPER = '/scaffolding-helper';
  static const ROAD_CONSTRUCTION_HELPER = '/road-construction-helper';
  static const PROFESSIONAL_PLUMBER = '/professional-plumber';
  static const PROFESSIONAL_PROFILE = '/professional-profile';
  static const HELPER_PROFILE = '/helper-profile';
  static const EDIT_PROFILE = '/edit-profile';
  static const ADD_ADDRESS = '/add-address';
  static const VERIFICATION = '/verification';
  static const CHAT_SCREEN = '/chat-screen';
  static const BOOKING_CONFIRM = '/booking-confirm';
  static const SERVICE_COMPLETED = '/service-completed';
  static const SERVICE_COMPLETED_SUCCESSFULLY =
      '/service-completed-successfully';
  static const ADDRESS_SCREEN = '/address-screen';
  static const PROVIDER_LOGIN = '/provider-login';
  static const PROVIDER_OTP = '/provider-otp';
  static const PROVIDER_LOCATION = '/provider-location';
  static const PROVIDER_PROFILE = '/provider-profile';
  static const PROVIDER_HOME = '/provider-home';
  static const ACTIVEJOB_SCREEN = '/activejob-screen';
  static const BOTTOM2 = '/bottom2';
  static const JOBS = '/jobs';
  static const PROVIDER_SETTING = '/provider-setting';
  static const PROVIDER_CHAT = '/provider-chat';
  static const PROVIDER_ACCOUNT = '/provider-account';
  static const PROVIDER_CHAT_SCREEN = '/provider-chat-screen';
  static const PROVIDER_EDIT_PROFILE = '/provider-edit-profile';
  static const JOB_DETAIL = '/job-detail';
  static const YOUR_EARNING = '/your-earning';
  static const JOBS_DETAILS = '/jobs-details';
  static const HELP_SUPPORT = '/help-support';
  static const USER_HELP = '/user-help';
  static const REQUEST_PANDDING = '/request-pandding';
  static const ABOUT_TASKEXPRESS = '/about-taskexpress';
  static const PRIVACYDATA_VIEW = '/privacydata-view';
}
